# 그룹: 비슷한 의미의 단어를 그룹으로 모을 수 있습니다.
# triggers 나 conditions의 keywords 에서 group:group_id 형태로 사용합니다.
groups:
  iu: '아이유, 지은, 징쨩'
  birthday: '생일, 태어나다'
  when: '날짜, 날, 언제, 며칠'
  get:
    - 받다
    - 얻다
  how:
    - 어떻게
    - 법

# (옵션) 아래 키워드를 모두 만족할 때 반응합니다.
# conditions 에서 공통의 키워드를 뽑을 때 사용합니다.
triggers:
  - group:iu

# 키워드와 대답
qnas:
  - keywords: '혈액형'
    answers: '아이유는 A형입니다.'
  - keywords: '데뷔, group:when'
    answers: '아이유 데뷔일은 2008년 9월 18일 입니다.'
  - keywords:
      - group:birthday
      - group:when
    answers: '아이유 생일은 1993년 5월 16일 입니다.'
  - keywords: '사랑, group:get, group:how'
    answers:
      - 그건 저도 알고 싶네요...
      - 알면 내가 사랑 받았지...
